#!/bin/bash

set -euo pipefail

RED="\033[1;\e[31m"
GREEN="\033[1;\e[32m"
LIGHTGREEN="\033[32m"

MAGNETA="\033[35m"
ITALICRED="\033[3;${RED}m"
NC="\033[0m"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "\n[+] $1\n"; }

info() { echo -e "${GREEN}[INFO] $* ${NC}\n"; }
warn() { echo -e "${YELLOW}[WARN] $* ${NC}\n"; }
# error() {
#     echo -e "${RED}[ERROR]${NC} $*";
#           exit 1}

command_exists() {
    command -v "$1" &>/dev/null
}

install_font() {
    local name="$1"
    local url="$2"
    local grep_pattern="$3"
    local tmp_file="/tmp/${name}.zip"

    info "Installing $name..."

    if fc-list | grep -qi "$grep_pattern"; then
        info "Downloading $name..."
        curl -o "$tmp_file" -L "$url"
        unzip "$tmp_file" -d ~/.local/share/fonts/
        rm "$tmp_file"

    else
        info "${MAGNETA}$name already installed, skipping.${NC}"
    fi
}

manual_package_install() {
    local package="$1"
    # local stem="${package%%.*}"
    local url="$2"

    info "Installing ${package}..."

    if ! command_exists "$package"; then
        local tmp_dir
        tmp_dir=$(mktemp -d)

        pushd "$tmp_dir" >/dev/null

        curl -L -o "$package" \
            "$url"

        type=$(file -b "$package")

        if [[ "$type" == *"Zip archive"* ]]; then
            echo "ZIP"
            unzip "$package"

        elif [[ "$type" == *"tar archive"* ]]; then
            echo "TAR"
            tar -xzf "$package"

        elif [[ "$type" == *"gzip compressed"* ]]; then
            echo "TAR.GZ"
            tar -xzf "$package"
        else
            echo "UNKNOWN"
        fi

        cp "$package" ~/.local/bin/

        popd >/dev/null

        rm -rf "$tmp_dir"
    else
        warn "${package} already installed, skipping."
    fi
}

init() {
    mkdir -p ~/.local/bin
    sudo dnf -y install dnf-plugins-core \
        curl gawk wget coreutils wget

    info "${LIGHTGREEN}Installing Starship ...${NC}"

    manual_package_install "starship" "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"

    info "${LIGHTGREEN}Enabling COPR repositories...${NC}"
    sudo dnf copr enable -y varlad/zellij || true
    sudo dnf copr enable -y dejan/lazygit || true
    sudo dnf copr enable -y alternateved/keyd || true

    # Enable RPM Fusion

    info "${GREEN}Adding RPM Fusion repositories...${NC}"
    FEDORA_VERSION=$(rpm -E %fedora)

    if ! rpm -q rpmfusion-free-release &>/dev/null; then
        sudo dnf install -y \
            https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"${FEDORA_VERSION}".noarch.rpm \
            https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"${FEDORA_VERSION}".noarch.rpm
    fi
}

# =========================
# Install Fonts
# =========================

install-fonts() {
    mkdir -p ~/.local/share/fonts/

    install_font "MapleMonoNF" \
        "https://github.com/subframe7536/maple-font/releases/latest/download/MapleMono-NF-unhinted.zip" \
        "maple"

    install_font "mononoki" \
        "https://github.com/madmalik/mononoki/releases/latest/download/mononoki.zip" \
        "mononoki"

    install_font "nerdfontsymbols" \
        "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/NerdFontsSymbolsOnly.zip" \
        "symbols"

    fc-cache -vf ~/.local/share/fonts/
    fc-list : family style | grep -i maple
    fc-list : family style | grep -i mononoki
    fc-list : family style | grep -i 'symbols nerd font'
}

# =========================
# Install Docker
# =========================

install-docker() {
    info "${GREEN}Installing Docker...${NC}"

    sudo dnf remove -y docker docker-client \
        docker-client-latest docker-common \
        docker-latest docker-latest-inforotate docker-logrotate \
        docker-selinux docker-engine-selinux docker-engine

    sudo dnf-3 config-manager --add-repo \
        https://download.docker.com/linux/fedora/docker-ce.repo

    sudo dnf install -y \
        docker-ce docker-ce-cli \
        containerd.io docker-buildx-plugin \
        docker-compose-plugin

    sudo systemctl enable --now docker
    sudo systemctl start docker

    # sudo groupadd docker
    # sudo usermod -aG docker $USER
    # newgrp docker

    info "${GREEN}Testing Docker... ${NC}"
    sudo docker run hello-world

}

# =========================
# Install multimedia codecs
# =========================

install-codecs() {
    info "${GREEN}Installing Media Codecs... ${NC}"

    sudo dnf install -y \
        ffmpeg ffmpeg-libs --allowerasing

    sudo dnf group install -y \
        sound-and-video
}

# =========================
# Remove unwanted packages
# =========================

remove-packages() {
    info "${RED}Uninstalling packages...${NC}"

    pkgs=(plasma-discover dragon elisa-player)
    installed=()

    for p in "${pkgs[@]}"; do rpm -q "$p" &>/dev/null && installed+=("$p"); done

    [ ${#installed[@]} -gt 0 ] && sudo dnf rm -y "${installed[@]}"

    sudo dnf rm -y \
        plasma-discover dragon elisa

    sudo dnf group remove -y \
        kde-apps kde-pim kde-media
}

# =========================
# Install packages
# =========================

install-packages() {
    info "${GREEN}Installing packages...${NC}"

    manual_package_install "eza" "https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz"

    sudo dnf install -y \
        kitty qbittorrent obs-studio mpv \
        btop fastfetch chezmoi ncdu bat fd \
        zoxide dust chafa fish
}

install-keyd() {
    sudo dnf in -y keyd
    sudo systemctl enable keyd

    echo -e "[ids]\n*\n[main]\ncapslock = escape\nescape = capslock\n" | sudo tee /etc/keyd/default.conf >/dev/null

    sudo systemctl restart keyd
}

install-music() {
    info "${GREEN}Installing Music packages...${NC}"

    sudo dnf install -y \
        qsynth vmpk strawberry
}

install-dev() {
    info "${GREEN}Initializing Dev Environment${NC}"

    manual_package_install "neovide" "https://github.com/neovide/neovide/releases/latest/download/neovide.AppImage"

    sudo dnf install -y clang-format \
        neovim lazygit tmux uv cmake gcc \
        tmux zellij make pipx

    sudo dnf group install -y \
        c-development development-tools
}

install-doom() {
    info "Installing Doom Emacs..."

    if ! test -d ~/.config/emacs/; then
        git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
        ~/.config/emacs/bin/doom install
    else
        warn "Doom Emacs already installed, skipping."
    fi
}

install-emacs() {
    info "Installing Emacs and dependencies..."

    sudo dnf in -y emacs pandoc shellcheck \
        shfmt pipx tree-sitter clang-format \
        bash-language-server

    manual_package_install "dasel" "https://github.com/TomWright/dasel/releases/latest/download/dasel_linux_amd64"

    pipx install isort pipenv black \
        pyflakes nose pytest ruff ty \
        ruff-lsp
}

install-vscode() {
    info "Installing Visual Studio Code..."

    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
        echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo >/dev/null

    sudo dnf install -y \
        code
}

for command in "$@"; do
    case $1 in

    all)
        init
        install-fonts
        remove-packages
        install-packages
        install-dev
        install-codecs
        install-docker
        install-vscode
        install-keyd
        install-emacs
        install-doom
        ;;

    keyd)
        install-keyd
        ;;

    fonts)
        install-fonts
        ;;

    code)
        install-vscode
        ;;

    init)
        remove-packages
        init
        install-packages
        ;;

    dev)
        install-dev
        ;;

    docker)
        install-docker
        ;;

    doom)
        install-doom
        ;;

    emacs)
        install-emacs
        ;;

    *)
        info "${RED}Invalid input...${NC}"
        info "Choose one of:
        ${LIGHTGREEN}init${NC}: Bootstrap new Fedora Environment.
        ${LIGHTGREEN}init-repos${NC}: Bootstrap useful repos.
        ${LIGHTGREEN}rm-packages${NC}: Remove packages I don't like.
        ${LIGHTGREEN}codecs${NC}: Bootstrap codecs.
        ${LIGHTGREEN}dev${NC}: Bootstrap Development Tools.
        ${LIGHTGREEN}code${NC}: Install Visual Studio Code.
        ${LIGHTGREEN}docker${NC}: Bootstrap Docker Installation.
        "
        ;;

    esac
done

info "${GREEN}Bootstrap complete!${NC}"
