command_timeout = 5000
scan_timeout = 5000
add_newline = true

[directory]
format = '[$path]($style) '
style = 'bold cyan'
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = true

[git_status]
style = 'bold bright-purple'

[git_metrics]
disabled = false

[character]
# format = '$symbol '
success_symbol = '[->](bold green)'
error_symbol = '[->](bold red)'
